name: April Fools

on:
  push:
    branches:
      - main

jobs:
  april-fools:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3

    - name: Run april-fools
      run: |
        # A script that messes up the code by randomly adding or removing lines
        python3 april_fools.py

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Messing up the code"
        git push
