name: April Fools

on:
  push:
    branches:
      - main

jobs:
  april-fools:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: main

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run the prank script
      run: python3 april_fools.py

    - name: Commit and push if README changed
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add README.md
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "🤡 April Fools prank triggered"
          git push origin main
        fi
