name: Detect Python File Push

on:
  push:
    branches:
      - main
    paths:
      - '**/*.py'

jobs:
  notify-python-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log Python file push
        run: echo "A Python file was pushed to the main branch!"