name: APRIL FOOLS

on: [ push ]

permissions:
  contents: write

jobs: 
  april-fools:
    runs-on: ubuntu-latest
    steps:
      - name: checking code
        uses: actions/checkout@v4

      - name: April-Fools!
        run: |
          for file in $(find . -name "*.py"); do
            echo "Pranking $file"
                # Replace keywords with typos
            sed -i 's/def/skibidi/g' "$file"
            sed -i 's/try/ohio/g' "$file"
            sed -i 's/except/BAKA/g' "$file"
            sed -i 's/flaot/jigglaooshnuckbang/g' "$file"
            sed -i 's/print/rahhhh/g' "$file"
            echo "# WORK HARDER!" >> "$file"
          done

      - name: Commit and Push the Messed Up Code
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Please work harder, you lazy bum"
          git push